version: '3'

services:
  backend:
    container_name: backend
    build: ./
    command: sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      gunicorn --bind 0.0.0.0:8000 --workers=4 --log-level=debug --capture-output --chdir=/ink config.wsgi:application"
    ports:
      - "8000:8000"
    volumes:
      - .:/ink
    restart: unless-stopped
    networks:
      main:

networks:
  main:
