# Generated by Django 5.0.2 on 2024-03-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_alter_category_description_alter_design_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(default=1, upload_to='designs'),
            preserve_default=False,
        ),
    ]
