# Generated by Django 5.0.2 on 2024-03-08 08:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('body', ckeditor.fields.RichTextField(max_length=1000)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
