# Generated by Django 5.0.2 on 2024-03-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default=1, upload_to='blog'),
            preserve_default=False,
        ),
    ]
