# Generated by Django 5.0.2 on 2024-03-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('short_description', models.CharField(max_length=80)),
                ('about_me', models.TextField(max_length=200)),
                ('cv_file', models.FileField(default='cv/default.pdf', upload_to='cv')),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
                ('phone', models.CharField(blank=True, max_length=80, null=True)),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=150, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=150, null=True)),
                ('telegram_link', models.CharField(blank=True, max_length=150, null=True)),
                ('whatsapp_link', models.CharField(blank=True, max_length=150, null=True)),
                ('my_transparent_img', models.ImageField(default='my_img/default.png', upload_to='my_img')),
                ('background_img', models.ImageField(default='background_img/default.png', upload_to='background_img')),
            ],
        ),
    ]
